version: '3'

services:
  denokweb:
    build:
      context: .
      dockerfile: ./Denok.Web/Dockerfile
    ports:
      - "9010:9010"
    depends_on:
      - mongodb
    networks:
      - denoknet
  
  denokred:
    build:
      context: .
      dockerfile: ./Denok.Redirector/Dockerfile
    ports:
      - "9011:9011"
    depends_on:
      - mongodb
    networks:
      - denoknet

  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=denokdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./scripts/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./volumes/mongodb:/data/db
    networks:
      - denoknet
    ports:
      - 27017:27017
    command: mongod --auth

  # postgres:
  #   container_name: postgres
  #   working_dir: /usr/app
  #   volumes:
  #     - ./volumes/postgres_data:/var/lib/postgresql/data
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=netapi
  #     - POSTGRES_PASSWORD=netapi1234
  #     - POSTGRES_DB=netapi
  #     - PGDATA=/tmp
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - denoknet

  # redis:
  #   image: "redis:3.0-alpine"
  #   command: redis-server --requirepass devpass
  #   volumes:
  #     - "./volumes/redis:/data"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - denoknet
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - denoknet
networks:
  denoknet:
    driver: bridge